### ISSUE TITLE
小建议：秋招篇可以放在前面了

### ISSUE THREAD

**Issue by arglone** [NAOSI-DLUT/Campus2024#112]
感谢站长的工作。
但是目前即将步入6月下旬，7月后，秋招提前批即将拉开序幕。同时，现在暑期实习的招聘工作基本已步入尾声，所以站长是否考虑可以把“秋招篇”放到实习篇前面呢？或者至少做个目录？
一个小建议哈~😘

**Comment by li-ruida** [comment]
> 感谢站长的工作。 但是目前即将步入6月下旬，7月后，秋招提前批即将拉开序幕。同时，现在暑期实习的招聘工作基本已步入尾声，所以站长是否考虑可以把“秋招篇”放到实习篇前面呢？或者至少做个目录？ 一个小建议哈~😘

好的
