### ISSUE TITLE
25届实习

### ISSUE THREAD

**Issue by Yanyu0203** [NAOSI-DLUT/Campus2024#209]
请问后面还会做25届的实习秋招信息汇总帖吗？是否会新开一个仓库？谢谢

**Comment by li-ruida** [comment]
后续可能会考虑

**Comment by li-ruida** [comment]
> 请问后面还会做25届的实习秋招信息汇总帖吗？是否会新开一个仓库？谢谢

https://campus2025.top/
https://github.com/NAOSI-DLUT/Campus2025
好了,由于最近要做毕设,实在经历有限,欢迎大家一起来维护这个仓库,想要维护的同学可以加群869979067,参与维护的同学就业上有任何问题,都可以来问我,祝大家都能拿到满意的offer
