### ISSUE TITLE
25届暑期实习

### ISSUE THREAD

**Issue by Ys-OoO** [NAOSI-DLUT/Campus2024#212]
25届暑期实习快到了🥺，佬会更新25届的嘛

**Comment by li-ruida** [comment]
> 25届暑期实习快到了🥺，佬会更新25届的嘛

正在找人，如果可以找到帮忙维护的同学的话，会在暑期实习开始前创建 24届这个也很久没更新了，看看过阵子春招开始更新点中厂和大厂信息

**Comment by Ys-OoO** [comment]
好滴，感谢佬🤗！汇总的招聘信息实在不好找



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月29日 16:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [NAOSI-DLUT/Campus2024] 25届暑期实习 (Issue #212) |

25届暑期实习快到了🥺，佬会更新25届的嘛

正在找人，如果可以找到帮忙维护的同学的话，会在暑期实习开始前创建 24届这个也很久没更新了，看看过阵子春招开始更新点中厂和大厂信息

**Comment by GongyeLiu** [comment]
蹲，请问后面还会更新25届暑期/秋招的信息嘛🥺？非常感谢！

**Comment by cnkant** [comment]
> > 25届暑期实习快到了🥺，佬会更新25届的嘛
> 
> 正在找人，如果可以找到帮忙维护的同学的话，会在暑期实习开始前创建 24届这个也很久没更新了，看看过阵子春招开始更新点中厂和大厂信息

我可以帮忙维护大佬

**Comment by li-ruida** [comment]
> > > 25届暑期实习快到了🥺，佬会更新25届的嘛
> > 
> > 
> > 正在找人，如果可以找到帮忙维护的同学的话，会在暑期实习开始前创建 24届这个也很久没更新了，看看过阵子春招开始更新点中厂和大厂信息
> 
> 我可以帮忙维护大佬

那我晚点建个25仓库

**Comment by li-ruida** [comment]
https://campus2025.top/
https://github.com/NAOSI-DLUT/Campus2025
好了,由于最近要做毕设,实在经历有限,欢迎大家一起来维护这个仓库,想要维护的同学可以加群869979067,仅限真的想参与维护并且有时间的同学加入,参与维护的同学就业上有任何问题,都可以来问我,祝大家都能拿到满意的offer @GongyeLiu @cnkant @Ys-OoO @name1e5s
